spring:
  application:
    name: collection
  datasource:
    url: ${POSTGRES_HOST:jdbc:postgresql://localhost/collection}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres1}
    driverClassName: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:/db/migration
    url: ${POSTGRES_HOST:jdbc:postgresql://localhost/collection}
    user: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres1}
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        event:
          merge:
            entity_copy_observer: allow
  servlet:
    multipart:
      enabled: true
server:
  servlet:
    contextPath: /api
logging:
  level:
    root: info