name: Generate Manifest
description: Generate's k8s manifest
inputs:
  version:
    description: Version
    required: true
runs:
  using: composite
  steps:
    - name: Checkout Deploy Repo
      uses: actions/checkout@v3
      with:
        repository: monroeshindelar/kubernetes-manifests
        path: "./kubernetes-manifests"
        ssh-key: ""
        ssh-known-hosts: "github.com"
        ssh-strict: false

    - name: Install JKCFG
      shell: bash
      run: |
        curl -Lo jk https://github.com/jkcfg/jk/releases/download/0.4.0/jk-linux-${{ runner.arch.lowercase }}
        chmod +x jk
        yarn install --cwd deploy/kube

    - name: Generate
      shell: bash
      run: |
        ./jk run deploy/kube/collection.js -o deploy/kube -f deploy/kube/params/sunny.yaml -p version=${{ inputs.version }}