name: Generate Manifest
description: Generate's k8s manifest
inputs:
  version:
    description: Version
    required: true
runs:
  using: composite
  steps:


    - name: Install JKCFG
      shell: bash
      run: |
        curl -Lo jk https://github.com/jkcfg/jk/releases/download/0.4.0/jk-linux-amd64
        chmod +x jk
        yarn install --cwd deploy/kube

    - name: Generate
      shell: bash
      run: |
        ./jk run deploy/kube/collection.js -o deploy/kube -f deploy/kube/params/sunny.yaml -p version=${{ inputs.version }}