  name: Generate Manifest
  description: Generate's k8s manifest
  inputs:
    version:
      description: Version
      required: true
  runs:
    using: composite
    steps:
      - name: Checkout Deploy Repo
        uses: actions/checkout@v3
        with:
          repository: monroe-shindelar-org/k8s-deploy
          path: "./k8s_deploy"
          ssh-key: ${{ inputs.repo_access_token }}
          ssh-known-hosts: "github.com"
          ssh-strict: false

      - name: Install JKCFG
        shell: bash
        run: |
          curl -Lo jk https://github.com/jkcfg/jk/releases/download/0.4.0/jk-darwin-${{ runner.arch.lowercase }}
          chmod +x jk
          yarn install --cwd deploy/kube

      - name: Generate
        shell: bash
        run: |
          ./jk run deploy/kube/collection.js -o deploy/kube -f $file -p version=${{ inputs.version }}