name: Automated Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and Publish
        id: build_and_publish
        uses: ./.github/actions/docker_build_and_publish

      - name: Deploy
        uses: ./.github/actions/generate_manifest
        with:
          version: ${{ steps.build_and_publish.outputs.version }}
