name: Automated Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and Publish
        id: build_and_publish
        uses: ./.github/actions/docker_build_and_publish
        with:
          dockerhub_user: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Deploy
        uses: ./.github/actions/generate_manifest
        with:
          version: ${{ steps.build_and_publish.outputs.version }}

      - name: Push Manifest
        uses: ./.github/actions/push_manifest
        with:
          repo_access_token: ${{ secrets.REPO_ACCESS_TOKEN }}
