name: Deploy Snapshot
on:
  workflow_dispatch:
    inputs:
      version:
        description: Docker image version to deploy
        type: string

jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted
    steps:
      - name: Checkout
        using: actions/checkout@v3

      - name: Generate Manifest
        using: ./.github/actions/generate_manifest
