name: Deploy
on:
  workflow_call:
    inputs:
      version:
        description: "Version to deploy"
        type: string
  workflow_dispatch:
    inputs:
      version:
        description: "Version to deploy"
        type: string
        required: false

jobs:
  generate_manifest:
    name: Generate Manifest
    uses: ./.github/actions/generate_manifest
    with:
      version: ${{ inputs.version }}
