name: Deploy
on:
  workflow_call:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted
    steps:
      - name: Build and Publish
        uses: ./.github/workflows/docker_publish.yaml