name: Docker Publish
on:
  workflow_call:
    inputs:
      ref:
        description: "Git ref to build"
        type: string
        default: "main"
  workflow_dispatch:
    inputs:
      ref:
        description: "Git ref to build"
        type: string
        required: false

jobs:
  docker:
    name: Docker Publish
    runs-on: self-hosted
    outputs:
      version: ${{ steps.output_version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref || github.ref }}

      - name: Setup Java for ${{ runner.arch }}
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin
          architecture: ${{ runner.arch.lowercase }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582

      - name: Gradle Jar
        run: ./gradlew bootJar

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: monroeshindelar/collection
          tags: |
            type=semver,pattern={{version}},enabled={{ github.ref_type == 'tag' }}
            type=sha,prefix={{branch}}-

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          annotations: ${{ steps.meta.outputs.annotations }}

      - name: Output Version
        id: output_version
        run: echo "version=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}" >> "$GITHUB_OUTPUT"
